site_name: openaivec documentation
site_url: https://anaregdesign.github.io/openaivec/
theme:
  name: material

extra:
  analytics:
    provider: google
    property: G-J7N4M1XMRZ

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          docstring_style: google
          show_submodules: true

markdown_extensions:
  - pymdownx.superfences
