site_name: openaivec documentation
site_url: https://openaivec.anareg.design
site_description: Library for processing data using OpenAI, compatible with Pandas and Spark DataFrames.
keywords: Python, OpenAI, Pandas, Apache Spark, vectorization, embeddings, NLP
site_author: anaregdesign
theme:
  name: material
  features:
    - social

extra_files:
  - robots.txt

extra:
  analytics:
    provider: google
    property: G-J7N4M1XMRZ

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          docstring_style: google
          show_submodules: true

markdown_extensions:
  - pymdownx.superfences
