[tool.poetry]
name = "openaivec"
version = "0.1.5"
description = ""
authors = ["Hiroki Mizukami <hmizukami@microsoft.com>"]
license = "MIT License"
readme = "README.md"
packages = [
    { include = "openaivec", from = "." }
]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.56.2"
pytest = "^8.3.4"
pyspark = "^3.5.1"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
