[tool.poetry]
name = "vectorize-openai"
version = "0.1.0"
description = ""
authors = ["Hiroki Mizukami <hmizukami@microsoft.com>"]
license = "MIT License"
readme = "README.md"
packages = [
    { include = "openaivec", from = "." }
]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.3"
openai = "^1.56.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
