name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # vから始まるタグ（例: v1.2.3）

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 必要に応じて使用するPythonバージョンを指定

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Set version from Git tag
        shell: bash
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG#v}
          echo "Detected version: $VERSION"
          poetry version $VERSION

      - name: Install dependencies and build package
        run: poetry install && poetry build

      - name: Publish package to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build --no-interaction --username __token__
